### PR TITLE
eCO2 -> CO2

### LINKED ISSUE #4: Change various "estimated" references to "true"
Similar to this PR:
https://github.com/adafruit/Adafruit_SCD30/pull/5

Since the SCD30 is a "true" CO2 sensor and not an "estimated".

### PR DESCRIPTION
**Pull request by rpavlik**
This is a real CO2 sensor, so the docs and API should reflect that - see recent equivalent change to the arduino library. I opted to lowercase the property name now that we don't need mixed case to distinguish "e" from "CO2", so scd30.eCO2 is now just scd30.co2.

I also fixed some typos I saw as I was going thru.

Fixes #4

### CODE REVIEW

**Comment by tannewt** [comment]
Would you mind adding co2 to the design guide listing too? https://github.com/adafruit/circuitpython/blob/main/docs/design_guide.rst#sensor-properties-and-units Thanks!

**Comment by rpavlik** [comment]
I see that TVOC is in all caps. Do we want `CO2` in all caps too? or lowercase like most of the rest?

**Comment by ladyada** [comment]
CO2 is a technical spelling, i'd prefer its in all caps

**Comment by rpavlik** [comment]
OK, I'll revise this accordingly.

**Comment by ladyada** [comment]
thank you :)

**Comment by rpavlik** [comment]
OK, commits updated, and the docs PR is here: https://github.com/adafruit/circuitpython/pull/4070

**Comment by ladyada** [comment]
thanks, gonna wait till @tannewt is around and approves the new 'sensor type'

**Review by tannewt — APPROVED** [review]
CO2 looks good to me! Thank you!

**Pull request merged**
